### ISSUE TITLE
Activating every 25 seconds without MQTT messaging?

### ISSUE THREAD

**Issue by zorruno** [albertnis/mqcontrol#8] opened 2021-05-31 07:05 UTC
Hi (from Auckland), great utility thanks.

I'm running mqcontrol on Ubuntu 20.04.2 with systemd.  Mainly wanting screen locking for the desktop.  I struggled to figure out how to get root to lock a general user's screen but I have success with running the command as the user with su

``` 
-c "su - dave -c\"gnome-screensaver-command -l\"" 
```

The MQTT server is on a separate machine.

However, I get the situation that the screen locks every 25 seconds (seems consistent) even though there are no MQTT messages to that topic.  I can systemctl stop and restart mqcontrol and it will stop that behaviour, but if the machine reboots it will do the same.

monitoring journalctl shows me the below, and mosquitto_sub shows nothing at all to the topic (and I'm not publishing anything):

```
Apr 22 10:28:40 ubuntu2 mqcontrol[72165]: 2021/04/22 10:28:40 Message received on topic computers/ubuntu2/lockscreen:
Apr 22 10:28:40 ubuntu2 su[108743]: (to dave) root on none
Apr 22 10:28:40 ubuntu2 su[108743]: pam_unix(su-l:session): session opened for user dave by (uid=0)
Apr 22 10:28:41 ubuntu2 mqcontrol[72165]: 2021/04/22 10:28:41 Message received on topic computers/ubuntu2/lockscreen:
Apr 22 10:28:41 ubuntu2 su[108774]: (to dave) root on none
Apr 22 10:28:41 ubuntu2 su[108774]: pam_unix(su-l:session): session opened for user dave by (uid=0)
Apr 22 10:29:06 ubuntu2 mqcontrol[72165]: 2021/04/22 10:29:06 Message received on topic computers/ubuntu2/lockscreen:
Apr 22 10:29:06 ubuntu2 su[108953]: (to dave) root on none
Apr 22 10:29:06 ubuntu2 su[108953]: pam_unix(su-l:session): session opened for user dave by (uid=0)
Apr 22 10:29:31 ubuntu2 mqcontrol[72165]: 2021/04/22 10:29:31 Message received on topic computers/ubuntu2/lockscreen:
Apr 22 10:29:31 ubuntu2 su[109515]: (to dave) root on none
Apr 22 10:29:31 ubuntu2 su[109515]: pam_unix(su-l:session): session opened for user dave by (uid=0)
Apr 22 10:29:56 ubuntu2 mqcontrol[72165]: 2021/04/22 10:29:56 Message received on topic computers/ubuntu2/lockscreen:
Apr 22 10:29:56 ubuntu2 su[109690]: (to dave) root on none
```

Any ideas on what I'm missing?  Also, had you thought of running the command on a particular message to the topic only (rather than 'any' message?  I can have a look... this might be a simple way to fix it.

**Comment by albertnis** [comment] 2021-05-31 08:54
Hi there, thanks for raising an issue. I would love to get to get to the bottom of this. What's the full command you're running mqcontrol with (redact anything personal)? I wonder if perhaps it's subscribing to the wrong topic somehow. Is there much activity on other topics? Is it possible there's a message on another topic firing every 25 seconds?

**Comment by albertnis** [comment] 2021-05-31 09:59
> had you thought of running the command on a particular message to the topic only

I had thought of that, and actually have a couple of ways it could be run

1. Multiple `-c` parameters in a mapping format. So if you had a topic to turn the screen on and off for example, you could provide `-c "on:xbacklight =100" -c "off:xbacklight =0"`. That might get weird with commands containing colons however.
2. A simple `-f` parameter to filter incoming messages, perhaps even with regex support. So in your case if you're expecting to receive `on` the command would be expanded to `-c "su - dave -c\"gnome-screensaver-command -l\"" -f "on" `.

I think option 2 would be quite easy to implement. It's far from a direct solution to this problem, however...

**Comment by albertnis** [comment] 2021-05-31 10:06
> I can systemctl stop and restart mqcontrol and it will stop that behaviour, but if the machine reboots it will do the same.

This is the strangest part to me. If you run mqcontrol manually, without using systemd, does it work as desired every time?

**Comment by zorruno** [comment] 2021-06-04 04:11
Thanks for responding

> Is it possible there's a message on another topic firing every 25 seconds?

Hmm, I have tried to eliminate other things from firing off the topic.... and really don't think so.  I'm only using node red at this stage... one topic as above (I've searched for duplications).  Monitoring with `journalctl -u mqcontrol -r`  as above shows no data in that topic (blank) and I am definitely pushing the message `lock` to the topic (or not pushing anything).  I have put a switch topic before the payload so it is either `lock` with an incoming binary `0` or dropped.  When running properly I can clearly see the `lock` message in the journalctl log.

>If you run mqcontrol manually, without using systemd, does it work as desired every time?

I did have it running manually, but probably not long enough to test before setting up in systemd . I might have to run some more tests.  It has been a while since I tested each scenario. 

>I think option 2 would be quite easy to implement.

This would be a good workaround thanks... but of course I don't want to give up completely so again will test a few options first.

**Comment by zorruno** [comment] 2021-06-04 04:18
> What's the full command you're running mqcontrol with

this is what is in mqcontrol.service (with stuff redacted changed obviously)

```
[Unit]
Description=mqcontrol remote control

[Service]
Type=simple
ExecStart=/usr/local/bin/mqcontrol -i mqc-screenlock -c "su - dave -c \"gnome-screensaver-command -l\"" -h 192.168.12.34:1883 -t computers/ubuntu2/lockscreen

[Install]
WantedBy=multi-user.target
```

**Comment by zorruno** [comment] 2021-06-09 09:24
FYI... still running tests...

**Comment by zorruno** [comment] 2021-06-11 01:34
Something is definitely confused, and I'm pretty sure I've eliminated the node red elements.  It will work for a while (I'm pushing the keyword "lock", then feeding it a null 2 seconds later to be sure - verified in mqtt).  But it seems after the computer has been asleep for some time then wakes, it will continually relock the screen.  Interestingly, I can then set other values in mqtt, but the journalctl logs show it thinks the word "lock" is being published.  I thought it might be a mqtt retain issue or something, but it doesn't appear so.

it could definately be something with systemd, but I'm struggling to run the command without it... if I run the command directly as the user or as root, I get X session errors (Failed to get session bus: Cannot autolaunch D-Bus without X11 $DISPLAY).  I might first need to find a simpler, more reliable way of locking the screen.

**Comment by albertnis** [comment] 2021-06-12 04:50
Thanks for looking a bit more into this. A couple of thoughts: 

* Maybe a strange interaction with sleep/wake behaviour.
* The re-appearance of "lock" as a received message makes me think the message filtering flag proposed above might not fix the issue.

As a first pass I might try updating the dependencies. I've been pretty busy so haven't delved too far into reproducing this issue myself. But if you ever do find a way to reliably reproduce the issue, please let me know.

**Comment by albertnis** [comment] 2021-06-12 05:11
I've just pushed [v0.4.1](https://github.com/albertnis/mqcontrol/releases/tag/v0.4.1) which upgrades the MQTT client to the latest version. I'm not particularly hopeful that this fixes the issue, but could you please give it a try and see if there is any change in behaviour?

**Comment by zorruno** [comment] 2021-06-14 21:18
Well I really struggled to reliably repeat the issue... but I've been running tests without systemd and yes - it does look like some sort of systemd issue or other OS interaction.  I think I may have solved it with a simpler method of locking the screen - it has been reliable for 2 days so I'll post when it has been ok for a few more.  I have also grabbed v0.4.1 thanks so can't fully rule that out, but I really doubt it is an mqcontrol issue at all now, so thanks for your time looking at this.

After playing with it more I have a couple more suggestions for features, but don't feel you need to look at them, it is a great tool as is :) I'll add another thread with feature requests... if I was to get really motivated (or there was another lockdown...!) I'd learn some golang.

**Comment by albertnis** [comment] 2021-06-14 22:22
Thanks for the summary,  @zorruno. I'll close this issue now as our best guess is that this is not mqcontrol-related.

* Feel free to re-open if you become confident this is mqcontrol-related
* If you do learn the root cause (even if it's not mqcontrol-related) I would appreciate it if you could post it here. There may be some learnings worth adding to the docs, for example.
* I would love to discuss your feature requests. Please make a new issue for each feature suggestion and label it "enhancement".

Finally, thanks again for raising this. It's exciting to see mqcontrol being used "in the wild".

**Closed as completed by albertnis** 2021-06-14 22:22 UTC
Labels: bug

**Comment by zorruno** [comment] 2021-06-15 01:02
FYI for closure for those Ubuntu users, the command I'm using now (and it seems fine in systemd)

`mqcontrol -i mqc-screenlock -c "su - dave -c \"xdg-screensaver lock\"" -h 192.168.12.34:1883 -t computers/ubuntu2/lockscreen`

Also users should be aware if they are using multiple instances of mqcontrol at the same time, you MUST give a different client ID each time (otherwise it goes in a loop as the mqtt server tries to kick each instance off).  This is an MQTT requirement, not an mqcontrol issue. That caught me out briefly.

**Comment by albertnis** [comment] 2021-06-15 01:46
> if they are using multiple instances of mqcontrol at the same time, you MUST give a different client ID each time

Oh boy, I learnt that one the hard way. That's actually why the client ID parameter is mandatory unlike in earlier versions. I'll consider updating the docs accordingly.

**Comment by EduardoOliveira** [comment] 2021-11-23 23:12
Sorry to revive a closed issue, but I think its relevant information given the usage in the examples.
I'm using this software using systemd --user to allow access to the xOrg related stuff, there are some caveats with the loading life cycle. Here is the "documentation" I've followed to achieve display shutdown via mqtt https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg

**Comment by zorruno** [comment] 2021-12-01 10:24
@EduardoOliveira that's fantastic thanks.  I have it working and it seems consistent now.  I've also learned a lot about systemctl user sessions.  This is how I have my Ubuntu gnome session lock the screen, with the binary installed in  `/usr/local/bin` (and made executable)

1. Create the service file in ~/.config/systemd/user/mqcontrol.service

```
[Unit]
Description="mqcontrol - remote control from mqtt server"
BindsTo=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/local/bin/mqcontrol -i daves_mqcontrol -c "gnome-screensaver-command -l" -h 192.168.1.256:1883 -t computercommands/lounge/lockscreen
Restart=always

[Install]
WantedBy=default.target
```

2. Enable the user service with `systemctl --user enable mqcontrol` and it will place a symlink of the systemd file in
`~/.config/systemd/user/default.target.wants/mqcontrol.service`

3. make it active with `systemctl --user start mqcontrol` and it will start any time the user session starts

4.  If you change the unit file you need to run `systemctl --user daemon-reload` it will warn you if you haven't.

5. Start and stop the daemon with `systemctl --user start mqcontrol` and `systemctl --user stop mqcontrol`

6. Check to see if the daemon is still running with` ps aux |grep mqcontrol` and `systemctl --user status mqcontrol`

7. You can check the systemd log (and follow it changing) with `journalctl --user-unit mqcontrol -n 10 -f`

8. I haven't tried this, and there is not much point if you are trying to lock the screen... but to ensure a service starts on boot for the user rather than login, you can apparently use `loginctl enable-linger USERNAME`

**Comment by zorruno** [comment] 2021-12-12 04:31
further followup... in Ubuntu, sending` gnome-screensaver-command -l` didn't seem to be that reliable (sometimes locked out)

I've since changed to `xdg-screensaver lock` which seems more reliable
